GET http://localhost:3000/api/v1/products

###

POST http://localhost:3000/api/v1/products/
Content-Type: application/json

{
  "name":"New Product",
  "price": 7000,
  "image":"http://placeimg.com/640/480"
}

###

PATCH  http://localhost:3000/api/v1/products/111
Content-Type: application/json

{
  "price": 8000
}

###

DELETE http://localhost:3000/api/v1/products/704a04c1-2b3c-420a-a82a-22dd947cc2f3

###

GET http://localhost:3000/user

###

POST http://localhost:3000/user
Content-Type: application/json

{
    "name":"Rossmery"
}

###


GET http://localhost:3000/chat/61b2d4d46bd9c0c0774d7c7c

###

POST http://localhost:3000/chat
Content-Type: application/json

{
    "users":[
        "61b2d4d46bd9c0c0774d7c7c",
        "61b2e7d4d8434c6298792379"
    ]
}
